// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RayBus.Data;

#nullable disable

namespace RayBus.Migrations
{
    [DbContext(typeof(RayBusDbContext))]
    [Migration("20251203201650_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RayBus.Models.Entities.Bus", b =>
                {
                    b.Property<int>("BusID")
                        .HasColumnType("int");

                    b.Property<string>("BusModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LayoutType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BusID");

                    b.ToTable("Buses", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.CancellationReason", b =>
                {
                    b.Property<int>("ReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonID"));

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ReasonID");

                    b.ToTable("CancellationReasons", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityID");

                    b.HasIndex("CityName")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_CityName");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Completed");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PaymentID");

                    b.HasIndex("ReservationID")
                        .HasDatabaseName("IX_Payments_ReservationID");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<int?>("CancelReasonID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Reserved");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("CancelReasonID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reservations_Status");

                    b.HasIndex("TripID")
                        .HasDatabaseName("IX_Reservations_TripID");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_Reservations_UserID");

                    b.HasIndex("TripID", "SeatID");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.ReservationLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("ReservationID")
                        .HasDatabaseName("IX_ReservationLogs_ReservationID");

                    b.ToTable("ReservationLogs", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatID"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SeatNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SeatPosition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.Property<int?>("WagonID")
                        .HasColumnType("int");

                    b.HasKey("SeatID");

                    b.HasIndex("WagonID")
                        .HasDatabaseName("IX_Seats_WagonID");

                    b.HasIndex("VehicleID", "SeatNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Seats_Vehicle_SeatNo");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Setting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("SettingKey");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Station", b =>
                {
                    b.Property<int>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationID"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StationID");

                    b.HasIndex("CityID")
                        .HasDatabaseName("IX_Stations_CityID");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Terminal", b =>
                {
                    b.Property<int>("TerminalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminalID"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TerminalID");

                    b.HasIndex("CityID")
                        .HasDatabaseName("IX_Terminals_CityID");

                    b.ToTable("Terminals", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Train", b =>
                {
                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.Property<string>("TrainModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainID");

                    b.ToTable("Trains", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripID"));

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArrivalStationID")
                        .HasColumnType("int");

                    b.Property<int?>("ArrivalTerminalID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartureStationID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartureTerminalID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("FromCityID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("ToCityID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.HasIndex("ArrivalStationID");

                    b.HasIndex("ArrivalTerminalID");

                    b.HasIndex("DepartureStationID");

                    b.HasIndex("DepartureTerminalID");

                    b.HasIndex("ToCityID");

                    b.HasIndex("VehicleID", "DepartureDate")
                        .HasDatabaseName("IX_Trips_VehicleDate");

                    b.HasIndex("FromCityID", "ToCityID", "DepartureDate", "DepartureTime")
                        .HasDatabaseName("IX_Trips_FromToDate");

                    b.ToTable("Trips", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Trips_DifferentCities", "FromCityID <> ToCityID");
                        });
                });

            modelBuilder.Entity("RayBus.Models.Entities.TripLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ChangedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ChangedByUserID");

                    b.HasIndex("TripID")
                        .HasDatabaseName("IX_TripLogs_TripID");

                    b.ToTable("TripLogs", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.TripSeat", b =>
                {
                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripSeatID")
                        .HasColumnType("int");

                    b.HasKey("TripID", "SeatID");

                    b.HasAlternateKey("TripSeatID");

                    b.HasIndex("IsReserved")
                        .HasDatabaseName("IX_TripSeats_IsReserved");

                    b.HasIndex("SeatID");

                    b.HasIndex("TripID")
                        .HasDatabaseName("IX_TripSeats_TripID");

                    b.ToTable("TripSeats", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("RoleID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PlateOrCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehicleID");

                    b.HasIndex("VehicleType")
                        .HasDatabaseName("IX_Vehicles_Type");

                    b.ToTable("Vehicles", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Vehicles_Type", "VehicleType IN ('Bus','Train')");
                        });
                });

            modelBuilder.Entity("RayBus.Models.Entities.Wagon", b =>
                {
                    b.Property<int>("WagonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WagonID"));

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.Property<int>("WagonNo")
                        .HasColumnType("int");

                    b.HasKey("WagonID");

                    b.HasIndex("TrainID")
                        .HasDatabaseName("IX_Wagons_TrainID");

                    b.HasIndex("TrainID", "WagonNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Wagons_Train_WagonNo");

                    b.ToTable("Wagons", (string)null);
                });

            modelBuilder.Entity("RayBus.Models.Entities.Bus", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Vehicle", "Vehicle")
                        .WithOne("Bus")
                        .HasForeignKey("RayBus.Models.Entities.Bus", "BusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Payment", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Reservation", b =>
                {
                    b.HasOne("RayBus.Models.Entities.CancellationReason", "CancelReason")
                        .WithMany("Reservations")
                        .HasForeignKey("CancelReasonID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Trip", null)
                        .WithMany("Reservations")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.TripSeat", "TripSeat")
                        .WithMany("Reservations")
                        .HasForeignKey("TripID", "SeatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelReason");

                    b.Navigation("TripSeat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RayBus.Models.Entities.ReservationLog", b =>
                {
                    b.HasOne("RayBus.Models.Entities.User", "PerformedByUser")
                        .WithMany("ReservationLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Reservation", "Reservation")
                        .WithMany("ReservationLogs")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Seat", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("Seats")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.Wagon", "Wagon")
                        .WithMany("Seats")
                        .HasForeignKey("WagonID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Vehicle");

                    b.Navigation("Wagon");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Station", b =>
                {
                    b.HasOne("RayBus.Models.Entities.City", "City")
                        .WithMany("Stations")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Terminal", b =>
                {
                    b.HasOne("RayBus.Models.Entities.City", "City")
                        .WithMany("Terminals")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Train", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Vehicle", "Vehicle")
                        .WithOne("Train")
                        .HasForeignKey("RayBus.Models.Entities.Train", "TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Trip", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Station", "ArrivalStation")
                        .WithMany("ArrivalTrips")
                        .HasForeignKey("ArrivalStationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Terminal", "ArrivalTerminal")
                        .WithMany("ArrivalTrips")
                        .HasForeignKey("ArrivalTerminalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Station", "DepartureStation")
                        .WithMany("DepartureTrips")
                        .HasForeignKey("DepartureStationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Terminal", "DepartureTerminal")
                        .WithMany("DepartureTrips")
                        .HasForeignKey("DepartureTerminalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.City", "FromCity")
                        .WithMany("DepartureTrips")
                        .HasForeignKey("FromCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.City", "ToCity")
                        .WithMany("ArrivalTrips")
                        .HasForeignKey("ToCityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("ArrivalTerminal");

                    b.Navigation("DepartureStation");

                    b.Navigation("DepartureTerminal");

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RayBus.Models.Entities.TripLog", b =>
                {
                    b.HasOne("RayBus.Models.Entities.User", "ChangedByUser")
                        .WithMany("TripLogs")
                        .HasForeignKey("ChangedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RayBus.Models.Entities.Trip", "Trip")
                        .WithMany("TripLogs")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RayBus.Models.Entities.TripSeat", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Seat", "Seat")
                        .WithMany("TripSeats")
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RayBus.Models.Entities.Trip", "Trip")
                        .WithMany("TripSeats")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RayBus.Models.Entities.User", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Wagon", b =>
                {
                    b.HasOne("RayBus.Models.Entities.Train", "Train")
                        .WithMany("Wagons")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RayBus.Models.Entities.CancellationReason", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RayBus.Models.Entities.City", b =>
                {
                    b.Navigation("ArrivalTrips");

                    b.Navigation("DepartureTrips");

                    b.Navigation("Stations");

                    b.Navigation("Terminals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationLogs");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Seat", b =>
                {
                    b.Navigation("TripSeats");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Station", b =>
                {
                    b.Navigation("ArrivalTrips");

                    b.Navigation("DepartureTrips");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Terminal", b =>
                {
                    b.Navigation("ArrivalTrips");

                    b.Navigation("DepartureTrips");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Train", b =>
                {
                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Trip", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("TripLogs");

                    b.Navigation("TripSeats");
                });

            modelBuilder.Entity("RayBus.Models.Entities.TripSeat", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RayBus.Models.Entities.User", b =>
                {
                    b.Navigation("ReservationLogs");

                    b.Navigation("Reservations");

                    b.Navigation("TripLogs");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Vehicle", b =>
                {
                    b.Navigation("Bus");

                    b.Navigation("Seats");

                    b.Navigation("Train");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RayBus.Models.Entities.Wagon", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
